steps:
  - label: "Test Benchmark Build"
    command: |
      docker-compose -f buildkite/benchmark-test/docker-compose.yml build
      docker-compose -f buildkite/benchmark-test/docker-compose.yml run \
        benchmark-test bash buildkite/benchmark/utils.sh create_conda_env_and_run_benchmarks
